#!/usr/bin/env python3
"""
Build responsive WebP derivatives for every photograph in public/photos.

The site used to hand every device the same ~1400px JPEG: a phone rendering
a 112px catalog sliver still downloaded 487 kB. This generates a width
ladder in WebP, shrinks the JPEG originals to a fallback size for the few
browsers that still need one, and writes src/data/photoManifest.ts so the
components can emit srcset and intrinsic width/height without guessing.

    python3 scripts/optimize-photos.py

Needs Pillow only. Re-run after adding or replacing a photo.
"""
import json
import os
import re
from PIL import Image

SRC_DIR = 'public/photos'
LADDER = (320, 640, 960, 1440)
WEBP_Q = 78
# The JPEG is only a fallback for browsers without WebP, which by now means
# very old devices on small screens. It does not need to be large.
FALLBACK_W = 900
FALLBACK_Q = 76

manifest = {}
saved = 0

for name in sorted(os.listdir(SRC_DIR)):
    if not name.lower().endswith(('.jpg', '.jpeg')):
        continue
    path = os.path.join(SRC_DIR, name)
    before = os.path.getsize(path)
    stem = re.sub(r'\.jpe?g$', '', name, flags=re.I)

    with Image.open(path) as im:
        im = im.convert('RGB')
        w, h = im.size

        widths = [x for x in LADDER if x < w] + [w if w <= max(LADDER) else max(LADDER)]
        widths = sorted(set(widths))

        made = []
        for target in widths:
            out = os.path.join(SRC_DIR, f'{stem}-{target}.webp')
            scale = target / w
            resized = im.resize((target, max(1, round(h * scale))), Image.LANCZOS)
            resized.save(out, 'WEBP', quality=WEBP_Q, method=6)
            made.append(target)

        # shrink the JPEG in place to fallback size
        if w > FALLBACK_W:
            fb = im.resize((FALLBACK_W, max(1, round(h * FALLBACK_W / w))), Image.LANCZOS)
        else:
            fb = im
        fb.save(path, 'JPEG', quality=FALLBACK_Q, progressive=True, optimize=True)

    after = os.path.getsize(path)
    saved += before - after
    manifest[f'/photos/{name}'] = {'w': w, 'h': h, 'widths': made}

lines = [
    '/**',
    ' * Intrinsic size and the available WebP widths for every photograph.',
    ' *',
    ' * Generated by scripts/optimize-photos.py. Do not edit by hand: re-run',
    ' * the script after adding or replacing a photo. Components read this to',
    ' * emit srcset and width/height, which is what keeps phones off the',
    ' * full-size files and keeps images from shifting the layout as they load.',
    ' */',
    'export type PhotoMeta = { w: number; h: number; widths: number[] }',
    '',
    'export const photoManifest: Record<string, PhotoMeta> = ',
]
body = json.dumps(manifest, indent=2, sort_keys=True)
open('src/data/photoManifest.ts', 'w').write('\n'.join(lines) + body + '\n')

webp_bytes = sum(
    os.path.getsize(os.path.join(SRC_DIR, f))
    for f in os.listdir(SRC_DIR) if f.endswith('.webp')
)
print(f'{len(manifest)} photos, {sum(len(m["widths"]) for m in manifest.values())} webp derivatives')
print(f'jpeg fallbacks shrunk by {saved / 1024 / 1024:.1f} MB')
print(f'webp ladder total {webp_bytes / 1024 / 1024:.1f} MB')
