/**
 * Admin microcopy.
 *
 * Three languages on purpose: the panel is used day to day by the client in
 * Icelandic, English keeps it workable for whoever maintains the site, and
 * Romanian is there for the developer who builds it. The choice is per browser
 * and lives in localStorage.
 */

const is = {
  common: {
    save: 'Vista',
    saving: 'Vista…',
    saved: 'Vistað',
    cancel: 'Hætta við',
    delete: 'Eyða',
    confirm: 'Staðfesta',
    close: 'Loka',
    search: 'Leita',
    all: 'Allt',
    loading: 'Sæki gögn',
    none: 'Ekkert',
    copy: 'Afrita',
    copied: 'Afritað',
    optional: 'valfrjálst',
    required: 'Reitur má ekki vera tómur',
    back: 'Til baka',
  },
  login: {
    title: 'Stjórnborð',
    lead: 'Sláðu inn netfangið og lykilorðið til að opna stjórnborðið.',
    email: 'Netfang',
    password: 'Lykilorð',
    submit: 'Skrá inn',
    error: 'Rangt netfang eða lykilorð',
    locked: 'Of margar tilraunir. Reyndu aftur eftir {n} sek.',
    hint: 'Lykilorðinu er breytt í stillingum vefsins, ekki hér.',
  },
  nav: {
    dashboard: 'Yfirlit',
    enquiries: 'Fyrirspurnir',
    links: 'Hlekkir',
    posts: 'Greinar',
    settings: 'Stillingar',
    viewSite: 'Skoða vefinn',
    signOut: 'Útskrá',
    menu: 'Valmynd',
  },
  storage: {
    local: 'Vaframinni',
    cloud: 'Supabase',
    localNote: 'Gögnin eru aðeins í þessum vafra',
    cloudNote: 'Gögnin eru samnýtt milli tækja',
  },
  dashboard: {
    title: 'Yfirlit',
    lead: 'Heimsóknir á vefinn, hvaðan þær koma og hvaða síður eru lesnar.',
    range7: '7 dagar',
    range30: '30 dagar',
    range90: '90 dagar',
    visits: 'Flettingar',
    visitors: 'Heimsóknir',
    perDay: 'Á dag',
    campaignShare: 'Í gegnum hlekki',
    chart: 'Flettingar á dag',
    topPages: 'Vinsælustu síður',
    sources: 'Hvaðan gestir koma',
    campaigns: 'Hlekkir',
    languages: 'Tungumál',
    devices: 'Tæki',
    direct: 'Beint',
    empty: 'Engin gögn á þessu tímabili ennþá.',
    mobile: 'Sími',
    tablet: 'Spjaldtölva',
    desktop: 'Tölva',
    posts: 'Birtar greinar',
    links: 'Virkir hlekkir',
    enquiries: 'Fyrirspurnir',
    conversion: 'Fyrirspurnir á hverjar 100 heimsóknir',
    today: 'Í dag',
    vsPrevious: 'á móti fyrra tímabili',
    exportCsv: 'Sækja CSV',
  },
  enquiries: {
    title: 'Fyrirspurnir',
    lead: 'Allt sem sent er úr formum vefsins lendir hér, með hlekknum sem gesturinn kom í gegnum.',
    statusNew: 'Ný',
    statusOpen: 'Í vinnslu',
    statusDone: 'Afgreidd',
    empty: 'Engin fyrirspurn ennþá.',
    from: 'Frá',
    service: 'Þjónusta',
    source: 'Kom í gegnum',
    page: 'Síða',
    note: 'Athugasemd',
    notePlaceholder: 'Til dæmis: hringdi til baka, vill tilboð í 60 m²',
    markOpen: 'Setja í vinnslu',
    markDone: 'Merkja afgreidda',
    reopen: 'Opna aftur',
    deleteConfirm: 'Eyða fyrirspurninni endanlega?',
    call: 'Hringja',
    email: 'Svara í tölvupósti',
    viaMailto: 'Sent úr póstforriti',
    viaEmail: 'Sent í pósthólfið',
    viaFormspree: 'Sent í gegnum formið',
    mailtoNote:
      'Formið opnaði póstforrit gestsins. Það er ekki hægt að staðfesta að hann hafi ýtt á senda, svo hafðu samband við hann.',
    newCount: 'nýjar',
  },
  links: {
    title: 'Hlekkir',
    lead: 'Búðu til hlekk fyrir hverja auglýsingu eða færslu og sjáðu hvaðan gestirnir koma.',
    create: 'Nýr hlekkur',
    edit: 'Breyta hlekk',
    label: 'Heiti',
    labelHelp: 'Til dæmis: Facebook færsla í ágúst',
    target: 'Lendir á',
    customTarget: 'Önnur slóð',
    code: 'Kóði',
    codeHelp: 'Birtist í slóðinni. Bókstafir og tölur.',
    note: 'Athugasemd',
    created: 'Búinn til',
    clicks: 'Smellir',
    visits: 'Flettingar',
    shareUrl: 'Slóð til að deila',
    archive: 'Setja í geymslu',
    restore: 'Virkja aftur',
    archived: 'Í geymslu',
    active: 'Virkur',
    deleteConfirm: 'Eyða hlekknum og tölfræðinni sem fylgir honum?',
    empty: 'Enginn hlekkur ennþá. Búðu til þann fyrsta.',
    codeTaken: 'Þessi kóði er þegar í notkun',
    showArchived: 'Sýna geymda',
  },
  posts: {
    title: 'Greinar',
    lead: 'Skrifaðu á einu tungumáli, þýddu í hin tvö og birtu.',
    create: 'Ný grein',
    draft: 'Drög',
    published: 'Birt',
    updated: 'Uppfært',
    languages: 'Tungumál',
    edit: 'Breyta',
    deleteConfirm: 'Eyða greininni endanlega?',
    empty: 'Engin grein ennþá. Skrifaðu þá fyrstu.',
    searchPlaceholder: 'Leita í greinum',
    openPublic: 'Skoða á vefnum',
  },
  editor: {
    createTitle: 'Ný grein',
    editTitle: 'Breyta grein',
    back: 'Til baka í greinar',
    sourceLang: 'Skrifað á',
    postTitle: 'Fyrirsögn',
    slug: 'Slóð',
    excerpt: 'Inngangur',
    excerptHelp: 'Ein til tvær setningar. Birtist í listanum og í leitarniðurstöðum.',
    body: 'Texti',
    bodyHelp: '## fyrir millifyrirsögn, - fyrir punkta, **feitletrað**, [texti](slóð).',
    seoTitle: 'Titill fyrir leitarvélar',
    seoDescription: 'Lýsing fyrir leitarvélar',
    cover: 'Forsíðumynd',
    coverHelp: 'Slóð á mynd. Má sleppa.',
    tags: 'Merki',
    tagsHelp: 'Aðskilin með kommu.',
    write: 'Skrifa',
    preview: 'Forskoðun',
    translate: 'Þýða yfir á hin tungumálin',
    translateOne: 'Þýða',
    translating: 'Þýði…',
    translated: 'Þýtt',
    translateFailed: 'Þýðingin tókst ekki',
    translateOffline:
      'Sjálfvirk þýðing er ekki tengd. Settu ANTHROPIC_API_KEY í Vercel og þýðingin virkar. Þangað til má skrifa textann sjálfur eða afrita leiðbeiningar hér að neðan.',
    copyPrompt: 'Afrita fyrirmæli fyrir þýðingu',
    missing: 'Vantar',
    publish: 'Birta',
    unpublish: 'Taka úr birtingu',
    saveDraft: 'Vista drög',
    needTitle: 'Fyrirsögn vantar',
    needBody: 'Texta vantar',
    publishBlocked: 'Fylltu út fyrirsögn og texta á upprunatungumálinu áður en greinin er birt.',
    untranslatedNote: 'Greinin birtist aðeins á þeim tungumálum sem eru fullþýdd.',
    deleteConfirm: 'Eyða greininni endanlega?',
    unsaved: 'Óvistaðar breytingar',
  },
  settings: {
    title: 'Stillingar',
    lead: 'Geymsla, aðgangur og gögn.',
    storage: 'Geymsla',
    storageLocalBody:
      'Greinar, fyrirspurnir og tölfræði eru í þessum vafra. Það sem er skrifað hér sést ekki í öðru tæki og gestir sjá ekki greinar sem hafa verið skrifaðar hér.',
    storageCloudBody: 'Tengt við Supabase. Gögnin eru samnýtt milli tækja og greinar sjást öllum gestum.',
    storageHow: 'Til að tengja: keyrðu supabase/schema.sql og settu VITE_SUPABASE_URL og VITE_SUPABASE_ANON_KEY í umhverfið.',
    access: 'Aðgangur',
    accessBody:
      'Lykilorðið er athugað í vafranum. Það heldur stjórnborðinu frá gestum og leitarvélum. Þegar Supabase er tengt tekur alvöru innskráning við.',
    changePassword: 'Breyta lykilorði',
    changePasswordBody: 'Skrifaðu nýtt lykilorð, afritaðu gildið og settu það sem VITE_ADMIN_PASSWORD_HASH.',
    newPassword: 'Nýtt lykilorð',
    hashResult: 'Gildi til að setja í umhverfið',
    tracking: 'Talning',
    trackingBody:
      'Talningin er án vafrakaka og geymir enga persónugreinanlega hluti: slóð, tungumál, tækjagerð, uppruna. Slökktu á talningu fyrir þennan vafra svo þínar eigin heimsóknir bætist ekki við.',
    optOut: 'Telja ekki heimsóknir úr þessum vafra',
    data: 'Gögn',
    exportBody: 'Sæktu allar greinar, hlekki og fyrirspurnir sem eina skrá.',
    export: 'Sækja afrit',
    import: 'Lesa inn afrit',
    importDone: 'Afritið var lesið inn',
    importFailed: 'Skráin var ekki lesin',
    clearStats: 'Hreinsa tölfræði',
    clearStatsBody: 'Eyðir öllum flettingum og smellum. Greinar, hlekkir og fyrirspurnir haldast.',
    clearConfirm: 'Eyða allri tölfræði?',
    language: 'Tungumál stjórnborðs',
  },
}

type AdminCopy = typeof is

const en: AdminCopy = {
  common: {
    save: 'Save',
    saving: 'Saving…',
    saved: 'Saved',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    close: 'Close',
    search: 'Search',
    all: 'All',
    loading: 'Loading',
    none: 'None',
    copy: 'Copy',
    copied: 'Copied',
    optional: 'optional',
    required: 'This field cannot be empty',
    back: 'Back',
  },
  login: {
    title: 'Admin',
    lead: 'Enter the address and the password to open the panel.',
    email: 'Email address',
    password: 'Password',
    submit: 'Sign in',
    error: 'Wrong address or password',
    locked: 'Too many attempts. Try again in {n} sec.',
    hint: 'The password is changed in the site settings, not here.',
  },
  nav: {
    dashboard: 'Overview',
    enquiries: 'Enquiries',
    links: 'Links',
    posts: 'Posts',
    settings: 'Settings',
    viewSite: 'View site',
    signOut: 'Sign out',
    menu: 'Menu',
  },
  storage: {
    local: 'Browser storage',
    cloud: 'Supabase',
    localNote: 'Data stays in this browser',
    cloudNote: 'Data is shared across devices',
  },
  dashboard: {
    title: 'Overview',
    lead: 'Visits to the site, where they come from and which pages get read.',
    range7: '7 days',
    range30: '30 days',
    range90: '90 days',
    visits: 'Page views',
    visitors: 'Visits',
    perDay: 'Per day',
    campaignShare: 'Through links',
    chart: 'Page views per day',
    topPages: 'Top pages',
    sources: 'Where visitors come from',
    campaigns: 'Campaign links',
    languages: 'Languages',
    devices: 'Devices',
    direct: 'Direct',
    empty: 'No data in this period yet.',
    mobile: 'Phone',
    tablet: 'Tablet',
    desktop: 'Computer',
    posts: 'Published posts',
    links: 'Active links',
    enquiries: 'Enquiries',
    conversion: 'Enquiries per 100 visits',
    today: 'Today',
    vsPrevious: 'vs the previous period',
    exportCsv: 'Download CSV',
  },
  enquiries: {
    title: 'Enquiries',
    lead: 'Everything sent through the forms lands here, with the link the visitor arrived through.',
    statusNew: 'New',
    statusOpen: 'In progress',
    statusDone: 'Handled',
    empty: 'No enquiries yet.',
    from: 'From',
    service: 'Service',
    source: 'Arrived through',
    page: 'Page',
    note: 'Note',
    notePlaceholder: 'For example: called back, wants a quote for 60 m²',
    markOpen: 'Mark in progress',
    markDone: 'Mark handled',
    reopen: 'Reopen',
    deleteConfirm: 'Delete this enquiry for good?',
    call: 'Call',
    email: 'Reply by email',
    viaMailto: 'Sent from a mail client',
    viaEmail: 'Delivered to the inbox',
    viaFormspree: 'Sent through the form',
    mailtoNote:
      'The form opened the visitor’s mail client. There is no way to confirm they pressed send, so get in touch with them.',
    newCount: 'new',
  },
  links: {
    title: 'Links',
    lead: 'Make one link per advert or post and see where the visitors come from.',
    create: 'New link',
    edit: 'Edit link',
    label: 'Name',
    labelHelp: 'For example: Facebook post, August',
    target: 'Lands on',
    customTarget: 'Another path',
    code: 'Code',
    codeHelp: 'Appears in the URL. Letters and numbers.',
    note: 'Note',
    created: 'Created',
    clicks: 'Clicks',
    visits: 'Page views',
    shareUrl: 'Link to share',
    archive: 'Archive',
    restore: 'Reactivate',
    archived: 'Archived',
    active: 'Active',
    deleteConfirm: 'Delete this link and the statistics attached to it?',
    empty: 'No links yet. Create the first one.',
    codeTaken: 'That code is already in use',
    showArchived: 'Show archived',
  },
  posts: {
    title: 'Posts',
    lead: 'Write in one language, translate into the other two, publish.',
    create: 'New post',
    draft: 'Draft',
    published: 'Published',
    updated: 'Updated',
    languages: 'Languages',
    edit: 'Edit',
    deleteConfirm: 'Delete this post for good?',
    empty: 'No posts yet. Write the first one.',
    searchPlaceholder: 'Search posts',
    openPublic: 'View on the site',
  },
  editor: {
    createTitle: 'New post',
    editTitle: 'Edit post',
    back: 'Back to posts',
    sourceLang: 'Written in',
    postTitle: 'Title',
    slug: 'Slug',
    excerpt: 'Intro',
    excerptHelp: 'One or two sentences. Shown in the list and in search results.',
    body: 'Body',
    bodyHelp: '## for a subheading, - for bullets, **bold**, [text](url).',
    seoTitle: 'Search engine title',
    seoDescription: 'Search engine description',
    cover: 'Cover image',
    coverHelp: 'Image URL. Can be left empty.',
    tags: 'Tags',
    tagsHelp: 'Separated by commas.',
    write: 'Write',
    preview: 'Preview',
    translate: 'Translate into the other languages',
    translateOne: 'Translate',
    translating: 'Translating…',
    translated: 'Translated',
    translateFailed: 'The translation failed',
    translateOffline:
      'Automatic translation is not connected. Add ANTHROPIC_API_KEY in Vercel and it starts working. Until then write the text yourself or copy the prompt below.',
    copyPrompt: 'Copy translation prompt',
    missing: 'Missing',
    publish: 'Publish',
    unpublish: 'Unpublish',
    saveDraft: 'Save draft',
    needTitle: 'Title is missing',
    needBody: 'Body is missing',
    publishBlocked: 'Fill in the title and body in the source language before publishing.',
    untranslatedNote: 'A post only appears in the languages that are fully translated.',
    deleteConfirm: 'Delete this post for good?',
    unsaved: 'Unsaved changes',
  },
  settings: {
    title: 'Settings',
    lead: 'Storage, access and data.',
    storage: 'Storage',
    storageLocalBody:
      'Posts, enquiries and statistics live in this browser. What is written here is not visible on another device, and visitors do not see posts written here.',
    storageCloudBody: 'Connected to Supabase. Data is shared across devices and posts are visible to every visitor.',
    storageHow: 'To connect: run supabase/schema.sql, then set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in the environment.',
    access: 'Access',
    accessBody:
      'The password is checked in the browser. It keeps the panel away from visitors and search engines. Once Supabase is connected, real authentication takes over.',
    changePassword: 'Change the password',
    changePasswordBody: 'Type a new password, copy the value and set it as VITE_ADMIN_PASSWORD_HASH.',
    newPassword: 'New password',
    hashResult: 'Value to put in the environment',
    tracking: 'Counting',
    trackingBody:
      'Counting is cookieless and stores nothing that identifies a person: path, language, device class, source. Turn it off for this browser so your own visits do not add up.',
    optOut: 'Do not count visits from this browser',
    data: 'Data',
    exportBody: 'Download every post, link and enquiry as one file.',
    export: 'Download backup',
    import: 'Restore backup',
    importDone: 'The backup was restored',
    importFailed: 'The file could not be read',
    clearStats: 'Clear statistics',
    clearStatsBody: 'Deletes every page view and click. Posts, links and enquiries stay.',
    clearConfirm: 'Delete all statistics?',
    language: 'Panel language',
  },
}

const ro: AdminCopy = {
  common: {
    save: 'Salvează',
    saving: 'Se salvează…',
    saved: 'Salvat',
    cancel: 'Renunță',
    delete: 'Șterge',
    confirm: 'Confirmă',
    close: 'Închide',
    search: 'Caută',
    all: 'Toate',
    loading: 'Se încarcă',
    none: 'Nimic',
    copy: 'Copiază',
    copied: 'Copiat',
    optional: 'opțional',
    required: 'Câmpul nu poate fi gol',
    back: 'Înapoi',
  },
  login: {
    title: 'Panou de administrare',
    lead: 'Introdu adresa de email și parola ca să deschizi panoul.',
    email: 'Adresă de email',
    password: 'Parolă',
    submit: 'Intră',
    error: 'Adresă sau parolă greșită',
    locked: 'Prea multe încercări. Încearcă din nou peste {n} sec.',
    hint: 'Parola se schimbă în setările site-ului, nu aici.',
  },
  nav: {
    dashboard: 'Sumar',
    enquiries: 'Cereri',
    links: 'Linkuri',
    posts: 'Articole',
    settings: 'Setări',
    viewSite: 'Vezi site-ul',
    signOut: 'Ieși din cont',
    menu: 'Meniu',
  },
  storage: {
    local: 'Memoria browserului',
    cloud: 'Supabase',
    localNote: 'Datele rămân doar în acest browser',
    cloudNote: 'Datele sunt comune tuturor dispozitivelor',
  },
  dashboard: {
    title: 'Sumar',
    lead: 'Vizitele pe site, de unde vin și ce pagini se citesc.',
    range7: '7 zile',
    range30: '30 de zile',
    range90: '90 de zile',
    visits: 'Afișări',
    visitors: 'Vizite',
    perDay: 'Pe zi',
    campaignShare: 'Prin linkuri',
    chart: 'Afișări pe zi',
    topPages: 'Cele mai citite pagini',
    sources: 'De unde vin vizitatorii',
    campaigns: 'Linkuri de campanie',
    languages: 'Limbi',
    devices: 'Dispozitive',
    direct: 'Direct',
    empty: 'Încă nu sunt date pentru perioada aceasta.',
    mobile: 'Telefon',
    tablet: 'Tabletă',
    desktop: 'Calculator',
    posts: 'Articole publicate',
    links: 'Linkuri active',
    enquiries: 'Cereri',
    conversion: 'Cereri la 100 de vizite',
    today: 'Azi',
    vsPrevious: 'față de perioada anterioară',
    exportCsv: 'Descarcă CSV',
  },
  enquiries: {
    title: 'Cereri',
    lead: 'Tot ce se trimite din formularele site-ului ajunge aici, împreună cu linkul prin care a venit vizitatorul.',
    statusNew: 'Nouă',
    statusOpen: 'În lucru',
    statusDone: 'Rezolvată',
    empty: 'Încă nu e nicio cerere.',
    from: 'De la',
    service: 'Serviciu',
    source: 'A venit prin',
    page: 'Pagina',
    note: 'Notiță',
    notePlaceholder: 'De exemplu: sunat înapoi, vrea ofertă pentru 60 m²',
    markOpen: 'Trece în lucru',
    markDone: 'Marchează rezolvată',
    reopen: 'Redeschide',
    deleteConfirm: 'Ștergi definitiv cererea?',
    call: 'Sună',
    email: 'Răspunde pe email',
    viaMailto: 'Trimis din clientul de email',
    viaEmail: 'Livrat in inbox',
    viaFormspree: 'Trimis prin formular',
    mailtoNote:
      'Formularul a deschis clientul de email al vizitatorului. Nu se poate confirma că a apăsat trimite, deci contactează-l tu.',
    newCount: 'noi',
  },
  links: {
    title: 'Linkuri',
    lead: 'Fă câte un link pentru fiecare reclamă sau postare și vezi de unde vin vizitatorii.',
    create: 'Link nou',
    edit: 'Modifică linkul',
    label: 'Nume',
    labelHelp: 'De exemplu: postare Facebook, august',
    target: 'Duce la',
    customTarget: 'Altă adresă',
    code: 'Cod',
    codeHelp: 'Apare în adresă. Litere și cifre.',
    note: 'Notiță',
    created: 'Creat',
    clicks: 'Clicuri',
    visits: 'Afișări',
    shareUrl: 'Adresa de distribuit',
    archive: 'Pune în arhivă',
    restore: 'Reactivează',
    archived: 'Arhivat',
    active: 'Activ',
    deleteConfirm: 'Ștergi linkul și statistica lui?',
    empty: 'Încă niciun link. Fă-l pe primul.',
    codeTaken: 'Codul acesta e deja folosit',
    showArchived: 'Arată arhivate',
  },
  posts: {
    title: 'Articole',
    lead: 'Scrii într-o limbă, traduci în celelalte două, publici.',
    create: 'Articol nou',
    draft: 'Ciornă',
    published: 'Publicat',
    updated: 'Actualizat',
    languages: 'Limbi',
    edit: 'Modifică',
    deleteConfirm: 'Ștergi definitiv articolul?',
    empty: 'Încă niciun articol. Scrie-l pe primul.',
    searchPlaceholder: 'Caută în articole',
    openPublic: 'Vezi pe site',
  },
  editor: {
    createTitle: 'Articol nou',
    editTitle: 'Modifică articolul',
    back: 'Înapoi la articole',
    sourceLang: 'Scris în',
    postTitle: 'Titlu',
    slug: 'Adresă',
    excerpt: 'Introducere',
    excerptHelp: 'Una sau două fraze. Apare în listă și în rezultatele căutării.',
    body: 'Text',
    bodyHelp: '## pentru subtitlu, - pentru puncte, **îngroșat**, [text](adresă).',
    seoTitle: 'Titlu pentru motoarele de căutare',
    seoDescription: 'Descriere pentru motoarele de căutare',
    cover: 'Imagine principală',
    coverHelp: 'Adresa unei imagini. Poate rămâne gol.',
    tags: 'Etichete',
    tagsHelp: 'Separate prin virgulă.',
    write: 'Scrie',
    preview: 'Previzualizare',
    translate: 'Tradu în celelalte limbi',
    translateOne: 'Tradu',
    translating: 'Se traduce…',
    translated: 'Tradus',
    translateFailed: 'Traducerea nu a reușit',
    translateOffline:
      'Traducerea automată nu e conectată. Pune ANTHROPIC_API_KEY în Vercel și începe să meargă. Până atunci scrii textul tu sau copiezi instrucțiunile de mai jos.',
    copyPrompt: 'Copiază instrucțiunile de traducere',
    missing: 'Lipsește',
    publish: 'Publică',
    unpublish: 'Scoate din publicare',
    saveDraft: 'Salvează ciorna',
    needTitle: 'Lipsește titlul',
    needBody: 'Lipsește textul',
    publishBlocked: 'Completează titlul și textul în limba de origine înainte de publicare.',
    untranslatedNote: 'Articolul apare doar în limbile traduse complet.',
    deleteConfirm: 'Ștergi definitiv articolul?',
    unsaved: 'Modificări nesalvate',
  },
  settings: {
    title: 'Setări',
    lead: 'Stocare, acces și date.',
    storage: 'Stocare',
    storageLocalBody:
      'Articolele, cererile și statisticile stau în acest browser. Ce se scrie aici nu se vede pe alt dispozitiv, iar vizitatorii nu văd articolele scrise aici.',
    storageCloudBody: 'Conectat la Supabase. Datele sunt comune între dispozitive și articolele se văd la toți vizitatorii.',
    storageHow: 'Ca să conectezi: rulează supabase/schema.sql, apoi pune VITE_SUPABASE_URL și VITE_SUPABASE_ANON_KEY în mediu.',
    access: 'Acces',
    accessBody:
      'Parola e verificată în browser. Ține panoul departe de vizitatori și de motoarele de căutare. Când e conectat Supabase, intră autentificarea reală.',
    changePassword: 'Schimbă parola',
    changePasswordBody: 'Scrie parola nouă, copiază valoarea și pune-o ca VITE_ADMIN_PASSWORD_HASH.',
    newPassword: 'Parolă nouă',
    hashResult: 'Valoarea de pus în mediu',
    tracking: 'Numărătoare',
    trackingBody:
      'Numărătoarea e fără cookie-uri și nu ține nimic personal: adresa paginii, limba, tipul dispozitivului, sursa. Oprește-o pentru browserul acesta ca vizitele tale să nu se adune.',
    optOut: 'Nu număra vizitele din acest browser',
    data: 'Date',
    exportBody: 'Descarcă toate articolele, linkurile și cererile într-un singur fișier.',
    export: 'Descarcă copie',
    import: 'Încarcă o copie',
    importDone: 'Copia a fost încărcată',
    importFailed: 'Fișierul nu a putut fi citit',
    clearStats: 'Curăță statisticile',
    clearStatsBody: 'Șterge toate afișările și clicurile. Articolele, linkurile și cererile rămân.',
    clearConfirm: 'Ștergi toată statistica?',
    language: 'Limba panoului',
  },
}

export type AdminLang = 'is' | 'en' | 'ro'
export const ADMIN_LANGS: AdminLang[] = ['is', 'en', 'ro']
export const ADMIN_LANG_NAME: Record<AdminLang, string> = {
  is: 'Íslenska',
  en: 'English',
  ro: 'Română',
}
export const adminCopy: Record<AdminLang, AdminCopy> = { is, en, ro }

const LANG_KEY = 'epm.admin.lang'

export function readAdminLang(): AdminLang {
  try {
    const stored = localStorage.getItem(LANG_KEY)
    return stored === 'en' || stored === 'is' || stored === 'ro' ? stored : 'is'
  } catch {
    return 'is'
  }
}

export function writeAdminLang(lang: AdminLang): void {
  try {
    localStorage.setItem(LANG_KEY, lang)
  } catch {
    /* nothing to do */
  }
}
