/**
 * Intrinsic size and the available WebP widths for every photograph.
 *
 * Generated by scripts/optimize-photos.py. Do not edit by hand: re-run
 * the script after adding or replacing a photo. Components read this to
 * emit srcset and width/height, which is what keeps phones off the
 * full-size files and keeps images from shifting the layout as they load.
 */
export type PhotoMeta = { w: number; h: number; widths: number[] }

export const photoManifest: Record<string, PhotoMeta> = {
  "/photos/real-about-owner.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1050
    ]
  },
  "/photos/real-about-work.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1200
    ]
  },
  "/photos/real-after.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1050
    ]
  },
  "/photos/real-before.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1050
    ]
  },
  "/photos/real-contact.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1050
    ]
  },
  "/photos/real-hero-wide.jpg": {
    "h": 506,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1440
    ]
  },
  "/photos/real-hero.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1200
    ]
  },
  "/photos/real-home-break.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1200
    ]
  },
  "/photos/real-pano-1.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1050
    ]
  },
  "/photos/real-pano-2.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1050
    ]
  },
  "/photos/real-pano-3.jpg": {
    "h": 900,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1400
    ]
  },
  "/photos/real-pano-4.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1050
    ]
  },
  "/photos/real-pano-5.jpg": {
    "h": 900,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1400
    ]
  },
  "/photos/real-pf-1.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1050
    ]
  },
  "/photos/real-pf-break.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1200
    ]
  },
  "/photos/real-service-malun.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960
    ]
  },
  "/photos/real-service-parket.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1200
    ]
  },
  "/photos/real-service-slipun.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1200
    ]
  },
  "/photos/real-work-malun-2.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1050
    ]
  },
  "/photos/real-work-malun-3.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900,
      960,
      1200
    ]
  }
}
