/**
 * Intrinsic size and the available WebP widths for every photograph.
 *
 * Generated by scripts/optimize-photos.py. Do not edit by hand: re-run
 * the script after adding or replacing a photo. Components read this to
 * emit srcset and width/height, which is what keeps phones off the
 * full-size files and keeps images from shifting the layout as they load.
 */
export type PhotoMeta = { w: number; h: number; widths: number[] }

export const photoManifest: Record<string, PhotoMeta> = {
  "/photos/after-floor.jpg": {
    "h": 600,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/before-floor.jpg": {
    "h": 675,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/break-room-wide.jpg": {
    "h": 412,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/grain-askur.jpg": {
    "h": 663,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/grain-eik.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/grain-fura.jpg": {
    "h": 1600,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/grain-hnota.jpg": {
    "h": 1440,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/hero-herringbone-sun.jpg": {
    "h": 1350,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/hero-herringbone-wide.jpg": {
    "h": 506,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/pano-1-gardabaer-eik.jpg": {
    "h": 1350,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/pano-2-vesturbaer-sildarbein.jpg": {
    "h": 600,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/pano-3-karsnes-askur.jpg": {
    "h": 659,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/pano-4-mosfellsbaer-eik.jpg": {
    "h": 475,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/pano-5-grafarvogur-hnota.jpg": {
    "h": 675,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/parket-classic-ash.jpg": {
    "h": 900,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/parket-classic-latte.jpg": {
    "h": 900,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/parket-classic-mist.jpg": {
    "h": 900,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/parket-classic-mocha.jpg": {
    "h": 900,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/parket-design-taupe.jpg": {
    "h": 900,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/parket-eco-desert.jpg": {
    "h": 900,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/parket-eco-night.jpg": {
    "h": 900,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/parket-forest-bronze.jpg": {
    "h": 900,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/parket-royal-ridge.jpg": {
    "h": 900,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/real-about-owner.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/real-about-work.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/real-after.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/real-contact.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/real-hero.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/real-pano-5.jpg": {
    "h": 900,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/real-pf-1.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/real-pf-break.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/real-service-malun.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/real-service-parket.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/real-service-slipun.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/real-work-malun-2.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/real-work-malun-3.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/service-malun.jpg": {
    "h": 600,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/service-parket.jpg": {
    "h": 600,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/service-slipun.jpg": {
    "h": 600,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  }
}
