/**
 * Intrinsic size and the available WebP widths for every photograph.
 *
 * Generated by scripts/optimize-photos.py. Do not edit by hand: re-run
 * the script after adding or replacing a photo. Components read this to
 * emit srcset and width/height, which is what keeps phones off the
 * full-size files and keeps images from shifting the layout as they load.
 */
export type PhotoMeta = { w: number; h: number; widths: number[] }

export const photoManifest: Record<string, PhotoMeta> = {
  "/photos/after-floor.jpg": {
    "h": 933,
    "w": 1400,
    "widths": [
      320,
      640,
      960,
      1400
    ]
  },
  "/photos/before-floor.jpg": {
    "h": 1050,
    "w": 1400,
    "widths": [
      320,
      640,
      960,
      1400
    ]
  },
  "/photos/break-room-wide.jpg": {
    "h": 1100,
    "w": 2400,
    "widths": [
      320,
      640,
      960,
      1440
    ]
  },
  "/photos/grain-askur.jpg": {
    "h": 663,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/grain-eik.jpg": {
    "h": 1200,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/grain-fura.jpg": {
    "h": 1600,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/grain-hnota.jpg": {
    "h": 1440,
    "w": 900,
    "widths": [
      320,
      640,
      900
    ]
  },
  "/photos/hero-herringbone-sun.jpg": {
    "h": 1650,
    "w": 1100,
    "widths": [
      320,
      640,
      960,
      1100
    ]
  },
  "/photos/hero-herringbone-wide.jpg": {
    "h": 1350,
    "w": 2400,
    "widths": [
      320,
      640,
      960,
      1440
    ]
  },
  "/photos/pano-1-gardabaer-eik.jpg": {
    "h": 1800,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/pano-2-vesturbaer-sildarbein.jpg": {
    "h": 800,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/pano-3-karsnes-askur.jpg": {
    "h": 879,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/pano-4-mosfellsbaer-eik.jpg": {
    "h": 633,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/pano-5-grafarvogur-hnota.jpg": {
    "h": 900,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/real-about-owner.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-about-work.jpg": {
    "h": 1600,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/real-after.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-before.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-contact.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-hero-wide.jpg": {
    "h": 900,
    "w": 1600,
    "widths": [
      320,
      640,
      960,
      1440
    ]
  },
  "/photos/real-hero.jpg": {
    "h": 1600,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/real-home-break.jpg": {
    "h": 1600,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/real-pano-1.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-pano-2.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-pano-3.jpg": {
    "h": 1400,
    "w": 1400,
    "widths": [
      320,
      640,
      960,
      1400
    ]
  },
  "/photos/real-pano-4.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-pano-5.jpg": {
    "h": 1400,
    "w": 1400,
    "widths": [
      320,
      640,
      960,
      1400
    ]
  },
  "/photos/real-pf-1.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-pf-2.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-pf-3.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-pf-4.jpg": {
    "h": 1400,
    "w": 1400,
    "widths": [
      320,
      640,
      960,
      1400
    ]
  },
  "/photos/real-pf-5.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-pf-6.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-pf-7.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-pf-8.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-pf-9.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-pf-break.jpg": {
    "h": 1600,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/real-service-malun.jpg": {
    "h": 1280,
    "w": 960,
    "widths": [
      320,
      640,
      960
    ]
  },
  "/photos/real-service-parket.jpg": {
    "h": 1600,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/real-service-slipun.jpg": {
    "h": 1600,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/real-work-malun-2.jpg": {
    "h": 1400,
    "w": 1050,
    "widths": [
      320,
      640,
      960,
      1050
    ]
  },
  "/photos/real-work-malun-3.jpg": {
    "h": 1600,
    "w": 1200,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "/photos/service-malun.jpg": {
    "h": 1067,
    "w": 1600,
    "widths": [
      320,
      640,
      960,
      1440
    ]
  },
  "/photos/service-parket.jpg": {
    "h": 1067,
    "w": 1600,
    "widths": [
      320,
      640,
      960,
      1440
    ]
  },
  "/photos/service-slipun.jpg": {
    "h": 1067,
    "w": 1600,
    "widths": [
      320,
      640,
      960,
      1440
    ]
  }
}
